Version '3'
services:
  costruct:
    build:
      context: .
      dockerfile: dockerfile1
    volumes:
      - ./project/boxfuse-sample-java-war-hello/target/hello-1.0.war:/usr/local/tomcat/webapps/hello-1.0.war
  prod:
    build:
      context: .
      dockerfile: dockerfile2
    ports:
      - "8080:8080"
    volumes_from:
      -container:costruct
      -container:costruct:rw
