version: '2'
services:
  costruct:
    build:
      context: .
      dockerfile: dockerfile1
    volumes:
      - /usr/local/tomcat/webapps
  prod:
    build:
      context: .
      dockerfile: dockerfile2
    ports:
      - "8080:8080"
    volumes_from:
      -container:costruct
      -container:costruct:rw
